### ISSUE TITLE
require(...) is not a function

### ISSUE THREAD

**Issue by adamduffield** [clouedoc/puppeteer-extra-plugin-timezone#3]
When I use try to use this plugin with "puppeteer.use(require('puppeteer-extra-plugin-timezone')())"

I get:
![image](https://user-images.githubusercontent.com/37820062/126193014-bdebc78e-9bfc-411d-91c8-ba9df42444b5.png)

Any suggestions as to what I should look at to fix this?

If i console.log the plugin, i get: 
![image](https://user-images.githubusercontent.com/37820062/126194500-dfd97dc9-ca44-4157-bf3e-f84342635aec.png)

**System:**
    OS: macOS 11.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  Binaries:
    Node: 14.16.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.12 - /usr/local/bin/npm
  npmPackages:
    jest: ^27.0.6 => 27.0.6

**Comment by clouedoc** [comment]
Hello, thanks for using my plugin.

Try this: `puppeteer.use(require('puppeteer-extra-plugin-
timezone').default())`

And please let me know if it worked :)

Le lun. 19 juil. 2021 à 18:30, adamduffield ***@***.***> a
écrit :

**Comment by adamduffield** [comment]
Yes it works now. Thanks! 

Is there any way to get it working when using password authentication for the proxies? If not, no worries, I will just use IP auth :)

**Comment by clouedoc** [comment]
Glad that it works!

I did not configure a way to enable password authentication so you'll have
to use IP. However, you could edit the code and add an option for this :)

Le lun. 19 juil. 2021 à 21:00, adamduffield ***@***.***> a
écrit :

**Comment by EasyChris** [comment]
i have a same problems.

i use proxy for puppeteer config 

when i use  `puppeteer.use(require("puppeteer-extra-plugin-timezone")());`

it will some err `_(...) is not a function`

this is my launch config 

```
 args: [
        `--proxy-server=${proxy}`,
        "--disable-web-security",
        "--disable-features=IsolateOrigins,site-per-process",
        "-wait-for-browser",
        "--no-sandbox",
        "--disable-setuid-sandbox",
        // "--single-process",
        "--disable-dev-shm-usage",
        "--shm-size=3gb",
        "--disable-web-security",
        "--lang=en-US,en",
      ],
```

is there use proxy config to make this error?

My agent is a locally directly accessible similar 127.0.0.1 no verification

**Comment by clouedoc** [comment]
@EasyChris thanks for trying out my plugin

Try this:

```javascript
puppeteer.use(require("puppeteer-extra-plugin-timezone").default())
```

**Comment by clouedoc** [comment]
I'm going to close this issue in favour of #5 

@adamduffield Regarding the authentication issue, I've noted some implementation ideas in #4 

I'm too busy to contribute right now, but any help is welcome :)
